import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
test('single-container save unifies API bind/cache and preserves inference arguments; catalog includes configured models',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'sm75-unified-')),model=path.join(root,'model');fs.mkdirSync(model);fs.writeFileSync(path.join(model,'config.json'),JSON.stringify({model_type:'qwen',quantization_config:{quant_method:'fp8'}}));
 const child=spawn(process.execPath,[fileURLToPath(new URL('../server.mjs',import.meta.url))],{env:{...process.env,SM75_SINGLE_CONTAINER:'1',SM75_CONSOLE_ROOT:root,SM75_CONSOLE_HOST:'127.0.0.1',SM75_CONSOLE_PORT:'19265'},stdio:'ignore'});
 try{for(let i=0;i<80;i++){try{await fetch('http://127.0.0.1:19265/');break;}catch{await new Promise(r=>setTimeout(r,50));}}
 const headers={Authorization:'Bearer '+fs.readFileSync(path.join(root,'key'),'utf8').trim(),'Content-Type':'application/json'},base='http://127.0.0.1:19265/console-api/';const args=[model,'--host','127.0.0.1','--port','9000','--max-model-len','262144','--kv-transfer-config','{"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"spec_name":"CPUOffloadingSpec","cpu_bytes_to_use":8589934592}}','--speculative-config','{"method":"mtp","num_speculative_tokens":5}','--enable-auto-tool-choice','--tool-call-parser','qwen3_coder','--chat-template','/models/my template.jinja','--seed','42','--custom-json','{"label":"two words"}'];
 const response=await fetch(base+'profiles',{method:'POST',headers,body:JSON.stringify({id:'fixture',args,port:9000,format:'fp8',cacheRoot:path.join(root,'old-cache')})});assert.equal(response.status,200);const saved=(await response.json())[0];assert.equal(saved.port,8000);assert.equal(saved.args[saved.args.indexOf('--host')+1],'0.0.0.0');assert.equal(saved.args[saved.args.indexOf('--port')+1],'8000');assert.deepEqual(saved.args.slice(5),args.slice(5));const settings=await(await fetch(base+'settings',{headers})).json();assert.equal(saved.cacheRoot,settings.cacheRoot);
 const models=await(await fetch(base+'models',{headers})).json();assert.equal(models.find(x=>x.path===model).format,'fp8');
 }finally{child.kill();await new Promise(r=>child.once('exit',r));}
});
